import { StoreShell } from "@/components/store/StoreShell";
import { ArrowRight, Check, RefreshCw } from "lucide-react";
import { Link } from "wouter";

const labels = [["product", "Required. Marks a Blogger post as a store piece."], ["price-125000", "Required. Sets the storefront price; use an amount without separators."], ["currency-NGN", "Sets the live Paystack and storefront currency."], ["category-rings", "Creates the collection category filter."], ["collection-signature", "Creates the collection filter."], ["material-18k-gold", "Adds a material filter. Repeat for more than one material."], ["availability-in-stock", "Allows purchase. Use out-of-stock, preorder, or hidden as needed."], ["new-arrival", "Optional display badge. featured and sale are also supported."]];

export default function PublishingGuide() {
  return <StoreShell><main className="publishing-page"><PageTitle /><section className="publishing-flow"><div><span>01</span><h2>Create a Blogger post</h2><p>Write the product name as the title. Add a considered description, specifications, and high-quality image URLs in the post content.</p></div><div><span>02</span><h2>Add product labels</h2><p>Use the structured labels below. The system rejects non-product posts, missing prices, hidden pieces, and incomplete records that cannot be safely sold.</p></div><div><span>03</span><h2>Publish with confidence</h2><p>The catalog refreshes from Blogger every 15 seconds. Open collection pages also refresh automatically, so new eligible products appear as product cards—not as blog posts.</p></div></section><section className="label-guide"><div><p className="eyebrow">Product label convention</p><h2>Publishing becomes <i>professional classification.</i></h2><p>Labels can include or omit the `#` prefix. Write them in Blogger’s label field; shoppers never see the Blogger source.</p></div><div className="label-table">{labels.map(([label, description]) => <div key={label}><code>#{label}</code><p>{description}</p></div>)}</div></section><section className="publishing-note"><RefreshCw size={24} /><div><p className="eyebrow">The outcome</p><h2>One published post becomes a refined product page.</h2><p>La Glitz reads the post on the server, validates it, classifies its labels, extracts its images and description, assigns filters, and uses the server-held price to begin secure Paystack checkout.</p></div><Link className="primary-link" href="/shop">View the collection <ArrowRight size={17} /></Link></section><section className="publication-check"><p className="eyebrow">Before you publish</p><div><span><Check size={17} /> Product label and price added</span><span><Check size={17} /> Currency matches your Paystack account</span><span><Check size={17} /> Availability set to in stock</span></div></section></main></StoreShell>;
}

function PageTitle() { return <section className="info-header publishing-header"><p className="eyebrow">Blogger publishing guide</p><h1>Publish once.<br /><i>Appear beautifully.</i></h1><p>Blogger is the invisible product source. This guide shows how a post becomes a professionally classified La Glitz product.</p></section>; }
